services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: evaluations
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
